//=====-- cbgSubtarget.h - Define Subtarget for the CBG ----*- C++ -*-====//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the CBG specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef CBG_SUBTARGET_H
#define CBG_SUBTARGET_H

#include "llvm/Target/TargetSubtarget.h"
#include <string>

namespace llvm {

class cbgSubtarget : public TargetSubtarget {
  bool IsPins;
  
public:
  cbgSubtarget(const std::string &TT, const std::string &FS);

  bool usePredicatedInstructions() const { return IsPins; }
  
  /// ParseSubtargetFeatures - Parses features string setting specified 
  /// subtarget options.  Definition of function is auto generated by tblgen.
  std::string ParseSubtargetFeatures(const std::string &FS,
                                     const std::string &CPU);
  
  std::string getDataLayout() const {
    const char *p;
    p = "E-p:32:32:32-i64:64:64-f64:64:64-f128:64:64-n32";
    return std::string(p);
  }
};

} // end namespace llvm

#endif
